github: []
patreon: M4nd3l
open_collective: ""
ko_fi: m4nd3l
tidelift: ""
community_bridge: ""
liberapay: ""
issuehunt: ""
lfx_crowdfunding: ""
polar: ""
buy_me_a_coffee: ""
thanks_dev: ""
custom:
  - "https://www.paypal.com/donate/?hosted_button_id=LMSX6TAU9AQM4"
  - "https://dsc.gg/moremc-mod"
